#pragma once

#include <vector>
#include <map>
#include <atomic>
#include <mutex>
#include <condition_variable>
#include <queue>

#include "node_manager.h"
#include "sage_bytecode.h"

class SageSymbolTable;

typedef uint32_t table_index;

typedef int comptime_task_id ; // these will be generated by increment of ComptimeManager tasks.size()

enum class TaskResultType {
    VALUE,
    STRING_INJECTION,
    AST_INSERTION
};

struct ComptimeTask {
    vector<Command> task_instructions;
    vector<comptime_task_id> prerequisite_tasks;
    map<int, int> procedure_to_instruction_index;

    // string injection_string_result = ""; TODO: don't need this for when we implement compile time AST modification, just use the symbol_injection_value

    comptime_task_id task_id = -1;
    int associated_scope_id = -1;
    NodeIndex associated_ast_root = -1;
    TaskResultType result_type = TaskResultType::VALUE;
    SageValue symbol_injection_value = SageValue();

    ComptimeTask() {};
    ComptimeTask(comptime_task_id task_id, int scope_id, NodeIndex ast_root, TaskResultType result_type):
        task_id(task_id), associated_scope_id(scope_id), associated_ast_root(ast_root), result_type(result_type) {};
};

struct TaskComparator {
    bool operator()(const ComptimeTask *a, const ComptimeTask *b) {
        return a->prerequisite_tasks.size() > b->prerequisite_tasks.size();
    }
};

// TODO: need a way to resolve the type of comptime tasks so that we know what to query for from the interpreter when
//       when we do symbol table injection
typedef priority_queue<ComptimeTask *, vector<ComptimeTask *>, TaskComparator> TaskMinHeap;
struct ComptimeManager {
    NodeManager *node_man;

    vector<ComptimeTask> tasks;
    TaskMinHeap task_min_heap;
    map<NodeIndex, comptime_task_id> node_to_task_id;
    queue<ComptimeTask *> staged_for_execution;
    map<table_index, vector<uint8_t>> static_program_memory;

    mutex queue_mutex;
    condition_variable queue_condition_variable;
    atomic<int> tasks_completed{0};

    int execution_iterations = 0;
    static constexpr int MAX_ITERATIONS = 10;
    bool modifies_runtime_ast_lock = false;

    ComptimeManager() {};

    int get_next_task_prerequisite_count();
    void register_task_dependencies(SageSymbolTable &symbol_table);
    int add_task(NodeIndex);
    void execute_task(ComptimeTask *task);
    void execute_tasks_in_parallel(int thread_count);
    bool modifies_runtime_ast();
    bool verify_comptime_dependencies();
};















